# Action to use nmk builder
name: nmk
description: Invoke nmk builder
inputs:
    task:
        description: nmk task to be executed
        default: build
runs:
    using: docker
    image: Dockerfile
    args:
      - ${{ inputs.task }}
